sudo: required

services:
  - docker

before_install:
  # git version of backend needs cqp symlink, used in Docker image
  - ln -s ../lua-cqueues-pushy/cqp cqp
  # See https://hub.docker.com/r/rameplayerorg/rameplayer/
  - docker pull rameplayerorg/rameplayer
  - docker run -d -p 127.0.0.1:8000:8000 -v `pwd`:/opt/rame/rameplayer-backend rameplayerorg/rameplayer /bin/ash -c /etc/cqpushy/cqpushy.lua > container.id
  - docker ps -a
  - docker run rameplayerorg/rameplayer /bin/ash -c "ls -la / /opt /opt/rame /opt/rame/rameplayer-backend; ps auxf"

before_script:
  # wait backend server to get up
  - sleep 10

script:
  - ls -la / /opt .
  - netstat -a -l
  - docker ps -a
  - docker logs `cat container.id`
  - curl 'http://localhost:8000/lists/root'
