sudo: required

language: node_js

node_js:
  - '5.11'

services:
  - docker

# sshpass is needed so we can launch commands in Docker container
addons:
  apt:
    packages:
      - sshpass

before_install:
  # git version of backend needs cqp symlink, used in Docker image
  - ln -s ../lua-cqueues-pushy/cqp cqp
  # See https://hub.docker.com/r/rameplayerorg/rameplayer/
  - docker pull rameplayerorg/rameplayer
  # Run Docker image, and mount test videos to /media/mmcblk0p1/media
  - docker run -d -p 8000:8000 -p 8022:22 -v `pwd`:/opt/rame/rameplayer-backend -v `pwd`/test/videos:/media/mmcblk0p1/media rameplayerorg/rameplayer > /tmp/container.id

before_script:
  - cd test
  - npm install
  # wait backend server to get up
  - sleep 3

script:
  - cd test
  # run REST API tests with using Frisby.js
  - jasmine-node rest/01-initial/
  # restart backend
  - sshpass -p rpi ssh -p 8022 root@localhost "pkill lua5.3; supervisorctl start rameplayer-backend"
  # run more REST API tests
  - jasmine-node rest/02-after-restart/

after_script:
  - docker logs `cat /tmp/container.id`
