sudo: required

services:
  - docker

before_install:
- docker pull rameplayerorg/rameplayer
- docker run -d -p 127.0.0.1:8000:8000 rameplayerorg/rameplayer
- docker ps -a
- docker run rameplayerorg/rameplayer /bin/ash -c "ls -la / /opt"

script:
- ls -la / /opt
