sudo: required

services:
  - docker

before_install:
  # git version of backend needs cqp symlink, used in Docker image
  - ln -s ../lua-cqueues-pushy/cqp cqp
  # See https://hub.docker.com/r/rameplayerorg/rameplayer/
  - docker pull rameplayerorg/rameplayer
  # Run Docker image
  - docker run -d -p 127.0.0.1:8000:8000 -v `pwd`:/opt/rame/rameplayer-backend rameplayerorg/rameplayer > /tmp/container.id

before_script:
  # wait backend server to get up
  - sleep 3

script:
  - curl 'http://localhost:8000/lists/root'

after_script:
  - docker logs `cat /tmp/container.id`
